# Generated by Django 5.1.3 on 2024-11-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCalendario',
            fields=[
                ('idCalen', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('statusCalen', models.IntegerField()),
            ],
            options={
                'db_table': 'Calendario',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nome_curso', models.CharField(max_length=100)),
                ('statusPag_curso', models.CharField(max_length=20)),
                ('dias_curso', models.TextField()),
                ('horas_curso', models.IntegerField()),
                ('cliques_cursos', models.IntegerField(default=0)),
                ('resumo_curso', models.TextField()),
                ('descricao_curso', models.TextField()),
                ('tags_cursos', models.TextField()),
                ('tipo_curso', models.TextField()),
                ('imagem_curso', models.TextField()),
                ('status_curso', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numestrela', models.IntegerField()),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeForm', models.CharField(max_length=100)),
                ('emailForm', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('nomeCurso', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Formulario',
            },
        ),
        migrations.CreateModel(
            name='TagsCursos',
            fields=[
                ('id_tag', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TagsCursos',
            },
        ),
        migrations.CreateModel(
            name='TiposCursos',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TiposCursos',
            },
        ),
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('idTrilha', models.AutoField(primary_key=True, serialize=False)),
                ('nomeTri', models.CharField(max_length=255)),
                ('explicaTri', models.TextField()),
                ('cargaMinTri', models.IntegerField()),
                ('cargaMaxTri', models.IntegerField()),
                ('etapas', models.JSONField()),
                ('imageTri', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Trilha',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
