# Generated by Django 5.1.1 on 2024-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('status_curso', models.BooleanField()),
                ('statusPag_curso', models.CharField(max_length=20)),
                ('horas_curso', models.TimeField()),
                ('imagem_curso', models.BinaryField()),
                ('dataInicio_curso', models.DateField()),
                ('dataFim_curso', models.DateField()),
                ('descricao_curso', models.TextField()),
                ('programacao_curso', models.TextField()),
                ('requisitos_curso', models.TextField()),
                ('perfil_curso', models.TextField()),
                ('tags_cursos', models.TextField()),
                ('tipo_curso', models.TextField()),
            ],
        ),
    ]
