# Generated by Django 5.1.2 on 2024-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_feedback_formulario_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
    ]
