# Generated by Django 5.1.2 on 2024-10-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_rename_user_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='senha',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
    ]
