# Generated by Django 5.1.2 on 2024-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoCalendario',
            fields=[
                ('idCalen', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('dia', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('statusCalen', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=100)),
                ('statusPag_curso', models.CharField(max_length=20)),
                ('dias_curso', models.TextField()),
                ('horas_curso', models.IntegerField()),
                ('cliques_cursos', models.IntegerField(default=0)),
                ('resumo_curso', models.TextField()),
                ('descricao_curso', models.TextField()),
                ('tags_cursos', models.TextField()),
                ('tipo_curso', models.TextField()),
                ('imagem_curso', models.TextField()),
                ('status_curso', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Cursos',
            },
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
